// ХИТЫ ПРОДАЖ

export const HITS_SALES_FETCH_REQUEST = 'HITS_SALES_FETCH_REQUEST';
export const HITS_SALES_FETCH_SUCCESS = 'HITS_SALES_FETCH_SUCCESS';
export const HITS_SALES_FETCH_FAILURE = 'HITS_SALES_FETCH_FAILURE';

// КАРТОЧКА ТОВАРА

export const ITEM_FETCH_REQUEST = 'ITEM_FETCH_REQUEST';
export const ITEM_FETCH_FAILURE = 'ITEM_FETCH_FAILURE';
export const ITEM_FETCH_SUCCESS = 'ITEM_FETCH_SUCCESS';

// КАТАЛОГ

export const CATALOG_INIT = 'CATALOG_INIT'; // сброс глобального состояния каталога
export const CATALOG_FETCH_REQUEST = 'CATALOG_FETCH_REQUEST';
export const CATALOG_FETCH_FAILURE = 'CATALOG_FETCH_FAILURE';
export const CATALOG_FETCH_SUCCESS = 'CATALOG_FETCH_SUCCESS';
export const CATALOG_FETCH_CATEGORIES_SUCCESS = 'CATALOG_FETCH_CATEGORIES_SUCCESS';
export const CATALOG_FETCH_ITEMS_SUCCESS = 'CATALOG_FETCH_ITEMS_SUCCESS';
export const CATALOG_CATEGORY_CHANGE = 'CATALOG_CATEGORY_CHANGE';
export const CATALOG_SEARCH_CHANGE = 'CATALOG_SEARCH_CHANGE';

// КОРЗИНА

export const CART_SEND_INIT = 'CART_SEND_INIT'; // сброс глобального состояния корзины
export const CART_ADD_ITEM = 'CART_ADD_ITEM';
export const CART_REMOVE_ITEM = 'CART_REMOVE_ITEM';
export const CART_SEND_REQUEST = 'CART_SEND_REQUEST';
export const CART_SEND_FAILURE = 'CART_SEND_FAILURE';
export const CART_SEND_SUCCESS = 'CART_SEND_SUCCESS';

// ЛОКАЛЬНОЕ ХРАНИЛИЩЕ

export const STORAGE_CART_ORDERS = 'STORAGE_CART_ORDERS';