// ХИТЫ ПРОДАЖ

export const HITS_SALES_FETCH_REQUEST = 'HITS_SALES_FETCH_REQUEST';
export const HITS_SALES_FETCH_SUCCESS = 'HITS_SALES_FETCH_SUCCESS';
export const HITS_SALES_FETCH_FAILURE = 'HITS_SALES_FETCH_FAILURE';

// КАТАЛОГ

export const CATALOG_INIT = 'CATALOG_INIT';
export const CATALOG_FETCH_REQUEST = 'CATALOG_FETCH_REQUEST';
export const CATALOG_FETCH_FAILURE = 'CATALOG_FETCH_FAILURE';
export const CATALOG_FETCH_SUCCESS = 'CATALOG_FETCH_SUCCESS';
export const CATALOG_CATEGORY_CHANGE = 'CATALOG_CATEGORY_CHANGE';
export const CATALOG_SEARCH_CHANGE = 'CATALOG_SEARCH_CHANGE';

// КАРТОЧКА ТОВАРА

export const ITEM_FETCH_REQUEST = 'ITEM_FETCH_REQUEST';
export const ITEM_FETCH_FAILURE = 'ITEM_FETCH_FAILURE';
export const ITEM_FETCH_SUCCESS = 'ITEM_FETCH_SUCCESS';

// КОРЗИНА


